# -*- coding: utf-8 -*-
"""Untitled57.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WFyNotBrFcVvsO36VYSTVMk_jokoi_CB
"""

from bs4 import BeautifulSoup
import requests
import urllib.request
import json

all_logins = []
urls = []
for i in range(1, 9):
  url = 'https://github.com/search?q=security+location%3A%22Taiwan%22+&type=users&ref=advsearch&p=' + str(i)
  urls.append(url)


for j in urls:
    print(j)
    response = requests.get(j)

    if response.status_code == 200:
        try:
            data = response.json()
            logins = [user['login'] for user in data['payload']['results']]
            all_logins.extend(logins)
        except json.JSONDecodeError as e:
            print(f"Error decoding JSON: {e}")
    else:
        print(f"Request failed with status code: {response.status_code}")

serviceurl = 'https://api.github.com/users/'

results = []
for i in all_logins:
  url = serviceurl + i
  access_token = "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"
  headers = {'Authorization': 'Bearer ' + access_token}

  #print('Retrieving', url)
  req = urllib.request.Request(url, headers=headers)


  with urllib.request.urlopen(req) as response:
      data = response.read()
      js = json.loads(data.decode('utf-8'))

      # print(json.dumps(js, indent=4))
      if 'email' in js:
          # print(js["email"], '\n')
          result = js["email"]
          results.append(result)
      else:
          print("Email not available for this user.")

import pandas as pd
results_df = pd.DataFrame(results, columns=['email'])
final = results_df.dropna()
final.shape

final

final.to_csv("taiwan_devops.csv")